//
//  ViewController.m
//  reactTest
//
//  Created by 殷文昭 on 16/2/25.
//  Copyright © 2016年 Facebook. All rights reserved.
//

#import "ViewController.h"
#import <RCTRootView.h>
@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
  
  NSURL* jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  //
  //  /**
  //   * OPTION 2
  //   * Load from pre-bundled file on disk. The static bundle is automatically
  //   * generated by "Bundle React Native code and images" build step.
  //   */
  //
  ////   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  //
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"reactTest"
                                                 initialProperties:nil
                                                     launchOptions:nil];
  
  [self.view addSubview:rootView];
  CGSize screenSize = [UIScreen mainScreen].bounds.size;
  rootView.frame = CGRectMake(0, 0, screenSize.width, screenSize.height);
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

/*
#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
}
*/

@end
